- name: Restart Apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes
    daemon_reload: yes
